version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: Ecommerce-Project-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: NodeJS_midterm_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - Ecommerce-Project-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  # Backend Node.js API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: Ecommerce-Project-backend
    restart: always
    ports:
      - "5000:5000"  # Only for direct debugging access
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: NodeJS_midterm_db
      JWT_SECRET: 96555b9b-4a7e-43e4-87c3-93a2f0548264
      NODE_ENV: production
      LOG_LEVEL: debug  # For better troubleshooting
    volumes:
      - ./backend:/app  # Use bind mount for easier development
      - ./backend/public/uploads:/app/public/uploads
    networks:
      - Ecommerce-Project-network
    deploy:
      replicas: 2

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: Ecommerce-Project-frontend
    restart: always
    # No direct port exposure - will be accessed through nginx
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=/api  # Use relative URL for API calls
    networks:
      -Ecommerce-Project-network

  # Nginx as the main entry point
  nginx:
    image: nginx:latest
    container_name: Ecommerce-Project-nginx
    ports:
      - "80:80"  # Main application port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    depends_on:
      - backend
      - frontend
    networks:
      -Ecommerce-Project-network

networks:
 Ecommerce-Project-network:
    driver: bridge

volumes:
  mysql_data: